### ISSUE TITLE
CvComposer.exe already present after closing

### ISSUE THREAD

**Issue by gilprime** [wawanbreton/cvcomposer#2]
All is in the title... :wink:

**Comment by wawanbreton** [comment]
Affects version 1.0, is repeatable under Windows when a dockable image viewer is present and the main window is closed

**Comment by wawanbreton** [comment]
The issue was actually linked with the use of the Camera node, which instanciates OpenCV camera handles and never closed them. Now we wait for all the processings to be over, then cleanup the camera handles, then exit the application.
