### ISSUE TITLE
Parameter error when selecting 'Standard' method in Hough circle transform

### ISSUE THREAD

**Issue by acailly** [wawanbreton/cvcomposer#7]
The error:

```
C:\Users\10013618\Downloads\opencv\sources\modules\imgproc\src\hough.cpp:1284: error: (-5) Unrecognized method id in function cvHoughCircles
```

The .cvc file is attached
[bug.zip](https://github.com/wawanbreton/cvcomposer/files/670849/bug.zip)

**Comment by wawanbreton** [comment]
The provided list of methods is actually wrong, because the only implemented one is "gradient" => the method selection has been removed
